### PR TITLE
Created Courses page and its contents

### PR DESCRIPTION
**Pull request by umuthopeyildirim**
**Description:**
Created courses page to allow users to view all courses.

**Related issue:**
[Link](https://github.com/umuthopeyildirim/FlatironSchoolOpenSource/issues/6)

### CODE REVIEW

**Comment by umuthopeyildirim** [comment]
This is ready to merge with main IMO.  
Review it and merge it @igottheim

**Comment by igottheim** [comment]
The main page looks fine, well now need to open an issue for the individual data and how we create the backend

**Comment by umuthopeyildirim** [comment]
> The main page looks fine, well now need to open an issue for the individual data and how we create the backend

You can also create these issues.

**Review by igottheim — APPROVED** [review]
Looks fine to merge.

**Pull request merged**
