### PR TITLE
Frontend start

### PR DESCRIPTION
**Pull request by umuthopeyildirim**
My idea for react skin, when I mean skin instead of using Canvas expored front-end we create our own front-end that works like Canvas.

*    [x]  Find a way to reverse engineer `course-data.js`
*    [x]  Create a front-end using tailwindcss and daisy-ui

### CODE REVIEW

**Comment by umuthopeyildirim** [comment]
For Landing view;
- [ ] Create Footer 
- [ ] Create About Hero
- [ ] Create Our Mission Hero
- [ ] Create Lessons Hero

**Comment by umuthopeyildirim** [comment]
Do you want to merge this to Main or wanna rebranch it?

**Comment by igottheim** [comment]
lets finish front end before merging?

**Comment by umuthopeyildirim** [comment]
We also need to create newsletter but Revue is closing down.
Google 'better and not managed by Elon' newsletter companies.

**Comment by umuthopeyildirim** [comment]
Mobile is not great btw :dagger: 

Need to fix this using CSS media

**Comment by igottheim** [comment]
Front end mobile looks good. Only issue is removing the latin stuff.

**Comment by umuthopeyildirim** [comment]
> Front end mobile looks good. Only issue is removing the latin stuff.

Removed the latin stuff :D

**Comment by umuthopeyildirim** [comment]
@igottheim Please review this before mergin it with main.

**Comment by umuthopeyildirim** [comment]
Ready for merge! 
@igottheim

**Pull request merged**
